[project]
name = "fall-26-sdsu-backend"
version = "0.1.0"
description = "Backend for budget buddy."
readme = "README.md"
authors = [
    { name = "Ugur Emre Dogan", email = "ue.dogan@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.141.1",
    "requests>=2.34.2",
]

[project.scripts]
fall-26-sdsu-backend = "fall_26_sdsu_backend:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
